=== fuadsuyudi/fgka-cbir/.xml/images.dtd
<!ELEMENT images (image*)>
<!ELEMENT image (#PCDATA)>
<!ATTLIST image src CDATA #REQUIRED 
                rgb CDATA #REQUIRED
                cluster CDATA #REQUIRED>

=== fuadsuyudi/fgka-cbir/.xml/images.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE images SYSTEM "images.dtd">
<images>
  <image src="/home/yanu/images/image100.jpg" rgb="250 0 0 0 0 0 0 0 363 9 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 111 0 0 0 0 0 0 0 1422 84 1 0 0 0 0 0 228 176 14 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 80 0 0 0 0 0 0 0 1401 74 3 0 0 0 0 0 1098 1132 112 7 1 0 0 0 10 125 103 21 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 104 0 0 0 0 0 0 0 1119 132 4 0 0 0 0 0 865 1416 86 7 1 0 0 0 29 762 604 175 24 3 0 0 0 6 35 66 38 12 5 0 0 0 0 0 1 1 14 1365 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 62 1 0 0 0 0 0 0 581 133 8 0 0 0 0 0 429 1284 95 13 0 0 0 0 17 930 658 145 23 3 0 0 0 8 272 306 191 58 23 0 0 0 0 8 37 63 140 556 0 0 0 0 0 0 0 10 0 0 0 0 0 0 0 0 24 0 0 0 0 0 0 0 260 241 14 0 0 0 0 0 67 882 120 18 0 0 0 0 9 356 416 64 17 0 0 0 0 9 238 163 97 37 1 0 0 0 4 28 94 141 55 6 0 0 0 0 2 51 37 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 23 116 5 0 0 0 0 0 3 421 147 7 0 0 0 0 0 45 135 20 6 0 0 0 0 2 53 31 8 0 0 0 0 0 1 18 17 6 0 1 0 0 0 0 1 54 64 0 0 0 0 0 0 0 80 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 9 30 0 0 0 0 0 0 0 18 2 1 0 0 0 0 0 1 2 1 0 0 0 0 0 0 3 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 23 2" cluster="0"></image>
  <image src="/home/yanu/images/image101.jpg" rgb="4319 720 0 0 0 0 0 0 739 580 13 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 296 11 0 0 0 0 0 0 2176 799 51 0 0 0 0 0 145 215 161 30 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 63 0 0 0 0 0 0 0 909 193 2 0 0 0 0 0 689 994 192 34 0 0 0 0 6 69 40 137 15 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 349 102 2 0 0 0 0 0 611 920 115 0 0 0 0 0 55 454 366 182 21 0 0 0 0 1 35 24 76 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 104 53 2 0 0 0 0 0 259 661 71 0 0 0 0 0 68 606 346 40 1 0 0 0 4 54 182 201 167 4 0 0 0 0 4 18 77 48 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 1 0 0 0 0 0 0 33 347 49 0 0 0 0 0 10 439 370 19 0 0 0 0 0 67 265 234 53 0 0 0 0 5 28 148 425 354 15 0 0 0 0 4 5 49 45 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 33 4 0 0 0 0 0 0 69 297 14 0 0 0 0 0 12 253 82 6 0 0 0 0 0 14 181 96 116 2 0 0 0 4 12 13 187 92 4 0 0 0 0 0 0 4 28 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 12 3 0 0 0 0 0 0 44 32 1 0 0 0 0 0 4 48 5 0 0 0 0 0 1 1 9 0 0 0 0 0 0 0 0 0 0 23" cluster="0"></image>
  <image src="/home/yanu/images/image102.jpg" rgb="67 3 0 0 0 0 0 0 216 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 67 1 0 0 0 0 0 0 642 125 0 0 0 0 0 0 116 93 3 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0 0 0 0 0 0 0 440 58 1 0 0 0 0 0 430 371 52 18 5 2 0 0 11 84 49 20 27 28 47 0 0 0 0 0 1 146 2608 7 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 174 18 0 0 0 0 0 0 766 964 188 33 0 0 0 0 116 425 289 194 179 35 0 0 0 14 35 45 73 210 585 35 0 0 0 0 1 7 531 532 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 22 1 0 0 0 0 0 0 730 1174 190 5 0 0 0 0 163 1428 1111 422 92 8 0 0 2 135 251 197 245 115 11 0 0 1 4 17 48 75 108 33 0 0 0 0 0 3 18 10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 65 252 10 0 0 0 0 0 54 1425 1074 119 0 0 0 0 0 231 786 380 104 11 0 0 0 1 38 50 86 69 8 0 0 0 0 0 4 7 7 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 83 218 5 0 0 0 0 0 81 731 255 11 0 0 0 0 1 87 154 64 16 0 0 0 0 0 3 8 12 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 26 40 0 0 0 0 0 0 11 104 23 0 0 0 0 0 0 12 15 4 0 0 0 0 0 0 0 0 4 0" cluster="0"></image>
  <image src="/home/yanu/images/image103.jpg" rgb="1022 206 0 0 0 0 0 0 191 318 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 738 25 0 0 0 0 0 0 767 1283 68 0 0 0 0 0 36 273 171 21 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 788 2 0 0 0 0 0 0 2049 919 18 0 0 0 0 0 120 1163 896 81 0 0 0 0 0 47 188 221 88 0 0 0 0 0 0 2 9 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 23 0 0 0 0 0 0 0 1262 574 1 0 0 0 0 0 294 1612 719 45 0 0 0 0 0 188 480 537 216 1 0 0 0 0 1 33 363 193 0 0 0 0 0 0 0 18 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 80 34 0 0 0 0 0 0 149 970 283 5 0 0 0 0 5 193 657 384 42 1 0 0 0 0 42 120 376 257 0 0 0 0 0 1 14 360 312 0 0 0 0 0 0 0 41 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 58 10 0 0 0 0 0 0 99 247 68 5 0 0 0 0 1 36 92 155 21 0 0 0 0 0 0 55 155 159 0 0 0 0 0 0 12 191 234 0 0 0 0 0 0 0 40 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9 2 0 0 0 0 0 0 5 11 5 1 0 0 0 0 0 0 18 36 6 0 0 0 0 0 0 17 59 37 0 0 0 0 0 0 4 81 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 3 0 0 0 0 0 0 0 8 6 1 0 0 0 0 0 0 7 15" cluster="0"></image>
  <image src="/home/yanu/images/image104.jpg" rgb="327 8 0 0 0 0 0 0 171 54 11 0 0 0 0 0 0 0 3 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 167 1 0 0 0 0 0 0 1097 353 10 0 0 0 0 0 39 83 50 27 1 0 0 0 0 0 2 7 14 5 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 74 1 0 0 0 0 0 0 1238 257 3 0 0 0 0 0 311 640 138 48 7 0 0 0 1 18 40 55 50 34 0 0 0 0 0 1 3 46 50 1 0 0 0 0 0 0 1 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 57 0 0 0 0 0 0 0 1120 317 4 0 0 0 0 0 643 1292 168 43 1 0 0 0 12 202 216 150 126 41 0 0 0 1 4 28 84 229 266 28 0 0 0 0 0 5 190 2543 0 0 0 0 0 0 0 16 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 481 475 1 0 0 0 0 0 317 1966 229 23 0 0 0 0 10 641 503 197 98 13 0 0 0 23 88 65 132 253 150 10 0 0 0 0 5 67 417 494 0 0 0 0 0 0 5 91 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 28 169 1 0 0 0 0 0 31 1032 325 4 0 0 0 0 0 380 859 90 16 0 0 0 0 11 180 68 98 35 3 0 0 0 3 4 10 35 34 2 0 0 0 0 0 2 43 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0 0 0 0 0 0 0 79 136 1 0 0 0 0 0 83 463 35 1 0 0 0 0 5 75 74 13 0 0 0 0 0 0 3 4 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 0 0 0 0 0 0 0 14 8 0 0 0 0 0 0 3 10 0 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0" cluster="0"></image>
  <image src="/home/yanu/images/image105.jpg" rgb="583 1 0 0 0 0 0 0 595 62 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 223 3 0 0 0 0 0 0 1741 348 2 0 0 0 0 0 198 395 17 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 32 0 0 0 0 0 0 0 812 150 2 0 0 0 0 0 794 1222 157 0 0 0 0 0 16 185 144 29 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 264 38 1 0 0 0 0 0 679 1009 104 3 0 0 0 0 53 658 642 139 6 0 0 0 2 28 84 88 46 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 76 16 1 0 0 0 0 0 298 602 55 3 0 0 0 0 70 977 627 98 3 0 0 0 0 109 444 275 162 10 0 0 0 2 10 36 66 40 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 1 0 0 0 0 0 0 54 299 20 1 0 0 0 0 19 500 519 75 4 0 0 0 0 147 702 394 136 9 0 0 0 1 58 170 188 188 8 0 0 0 0 0 4 57 43 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 93 9 0 0 0 0 0 0 216 414 23 0 0 0 0 0 23 460 351 95 6 0 0 0 4 74 240 273 247 5 0 0 0 0 10 23 151 266 11 0 0 0 0 0 0 54 55 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 5 124 1 0 0 0 0 0 0 171 228 18 0 0 0 0 0 15 131 105 72 5 0 0 0 0 6 34 143 260 16 0 0 0 0 0 5 188 792" cluster="0"></image>
  <image src="/home/yanu/images/image106.jpg" rgb="251 0 0 0 0 0 0 0 537 19 0 0 0 0 0 0 3 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 34 0 0 0 0 0 0 0 1515 160 0 0 0 0 0 0 822 462 21 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 374 22 0 0 0 0 0 0 1288 1254 85 2 0 0 0 0 53 444 205 49 4 0 0 0 0 0 0 2 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 176 16 1 0 0 0 0 0 742 609 33 4 0 0 0 0 109 1462 691 127 42 0 0 0 0 58 210 154 178 27 0 0 0 0 0 0 6 5 2 464 0 0 0 0 0 0 1 68 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 103 21 0 0 0 0 0 0 279 480 38 3 0 0 0 0 111 1238 544 86 6 0 0 0 0 147 1399 432 160 43 5 0 0 0 93 37 122 221 55 106 0 0 0 0 0 6 19 279 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 59 23 0 0 0 0 0 0 23 365 29 2 0 0 0 0 8 601 411 45 5 0 0 0 0 139 557 199 72 9 2 0 0 0 20 207 191 127 44 6 0 0 0 0 6 82 74 61 0 0 0 0 0 0 1 54 0 0 0 0 0 0 0 0 1 15 0 0 0 0 0 0 0 140 26 0 0 0 0 0 0 37 188 10 0 0 0 0 0 18 156 78 15 2 0 0 0 0 8 27 80 33 10 0 0 0 0 0 49 94 213 26 0 0 0 0 0 1 90 48 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 10 0 0 0 0 0 0 0 17 1 0 0 0 0 0 0 1 4 0 0 0 0 0 0 2 1 12 10 0 0 0 0 0 0 5 26 24 2 0 0 0 0 0 2 93 732" cluster="0"></image>
